import { registerTool } from './registry';
import { fetchAssetTool } from './read/fetchAsset';
import { fetchProjectAssetsTool } from './read/fetchProjectAssets';
import { fetchProjectByIdTool } from './read/fetchProjectById';
import { fetchProjectEventsTool } from './read/fetchProjectEvents';
import { fetchProjectFilesTool } from './read/fetchProjectFiles';
import { fetchProjectWorkflowRunsTool } from './read/fetchProjectWorkflowRuns';
import { fetchProjectWorkflowsTool } from './read/fetchProjectWorkflows';
import { fetchJobStatusTool } from './read/fetchJobStatus';
import { fetchWorkflowByIdTool } from './read/fetchWorkflowById';
import { fetchWorkflowVersionsTool } from './read/fetchWorkflowVersions';
import { fetchNodeRunsTool } from './read/fetchNodeRuns';
import { searchAssetsTool } from './read/searchAssets';
import { findAssetsProducedByWorkflowRunTool } from './read/findAssetsProducedByWorkflowRun';
import { embedTextTool } from './read/embedText';
import { semanticSearchTool } from './read/semanticSearch';
import { proposeAddSceneTool } from './read/proposeAddScene';
import { proposeCreateWorkflowTool } from './read/proposeCreateWorkflow';
import { proposePatchStoryInputTool } from './read/proposePatchStoryInput';
import { proposeDeleteWorkflowTool } from './read/proposeDeleteWorkflow';
import { proposeDeprecateAssetTool } from './read/proposeDeprecateAsset';
import { pickWorkflowByNodeTypeTool } from './read/pickWorkflowByNodeType';
import { createAssetTool } from './write/createAsset';
import { createAssetVersionTool } from './write/createAssetVersion';
import { applyProposalTool } from './write/applyProposal';
import { createWorkflowTool } from './write/createWorkflow';
import { updateWorkflowTool } from './write/updateWorkflow';
import { createOutputTool } from './write/createOutput';
import { createWorkflowRunTool } from './exec/createWorkflowRun';
import { runWorkflowTool } from './exec/runWorkflow';
import { runWorkflowByNodeTypeTool } from './exec/runWorkflowByNodeType';
import { generateImageTool } from './exec/generateImage';
import { generateVideoTool } from './exec/generateVideo';
import { generateVideoFromImageTool } from './exec/generateVideoFromImage';
import { llmGenerateTextTool } from './exec/llmGenerateText';
import { waitForWorkflowRunTool } from './exec/waitForWorkflowRun';
import { generateVoiceOverTool } from './exec/generateVoiceOver';
import { generateSoundEffectTool } from './exec/generateSoundEffect';
import { verifyResultTool } from './exec/verifyResult';

let registered = false;

export function registerBuiltinTools() {
  if (registered) return;
  registered = true;

  registerTool(fetchProjectByIdTool);
  registerTool(fetchAssetTool);
  registerTool(fetchProjectAssetsTool);
  registerTool(fetchProjectWorkflowsTool);
  registerTool(fetchProjectWorkflowRunsTool);
  registerTool(fetchProjectEventsTool);
  registerTool(fetchProjectFilesTool);
  registerTool(fetchJobStatusTool);
  registerTool(fetchWorkflowByIdTool);
  registerTool(fetchWorkflowVersionsTool);
  registerTool(fetchNodeRunsTool);
  registerTool(searchAssetsTool);
  registerTool(findAssetsProducedByWorkflowRunTool);
  registerTool(embedTextTool);
  registerTool(semanticSearchTool);
  registerTool(proposeCreateWorkflowTool);
  registerTool(proposePatchStoryInputTool);
  registerTool(proposeAddSceneTool);
  registerTool(proposeDeleteWorkflowTool);
  registerTool(proposeDeprecateAssetTool);
  registerTool(pickWorkflowByNodeTypeTool);
  registerTool(createAssetTool);
  registerTool(createAssetVersionTool);
  registerTool(applyProposalTool);
  registerTool(createWorkflowTool);
  registerTool(updateWorkflowTool);
  registerTool(createOutputTool);
  registerTool(createWorkflowRunTool);
  registerTool(runWorkflowTool);
  registerTool(runWorkflowByNodeTypeTool);
  registerTool(waitForWorkflowRunTool);
  registerTool(llmGenerateTextTool);
  registerTool(generateImageTool);
  registerTool(generateVideoTool);
  registerTool(generateVideoFromImageTool);
  registerTool(generateVoiceOverTool);
  registerTool(generateSoundEffectTool);
  registerTool(verifyResultTool);
}
